server:
  port: 8081
spring:
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    encoding: UTF-8
    mode: HTML5
    suffix: .html
  resources: 
    static-locations: classpath:/static/
    cache: 
      period: 0
    

#spring:#  datasource:#    driver-class-name: 'com.microsoft.sqlserver.jdbc.SQLServerDriver'
#    url: 'jdbc:sqlserver://localhost;databaseName=kandawaps'
#    username: 'kanda'
#    password: 'kanda1723'
#  jpa: 
#    show-sql: true
#    properties: 
#      hibernate:
#       format_sql: true
#       dialect: 'org.hibernate.dialect.SQLServer2012Dialect'
#       ddl-auto: 'update'
##關閉 Thymeleaf 的快取開發過程中無需重啟
#spring.thymeleaf.cache = false
##設定thymeleaf頁面的編碼
#spring.thymeleaf.encoding=UTF-8
#spring.thymeleaf.mode=HTML5
##設定thymeleaf頁面的字尾
#spring.thymeleaf.suffix=.html
##設定thymeleaf頁面的儲存路徑
#spring.thymeleaf.prefix=classpath:/templates/

#server.port=8080 
#server.session.timeout=10 
#server.tomcat.uri-encoding=UTF-8 
#spring.thymeleaf.prefix=classpath:/views/ 
#spring.thymeleaf.suffix=.html 
#spring.thymeleaf.mode=HTML5 
#spring.thymeleaf.encoding=UTF-8 
#spring.thymeleaf.content-type=text/html 
#spring.thymeleaf.cache=false 







