mainTableCols = [{
    checkbox: true
}, {
    field: 'no',
    title: '編號'
}, {
    field: 'customType',
    title: '自然人/法人'
}, {
    field: 'shinto',
    title: '信託'
}, {
    field: 'customNo',
    title: '身分證/統編'
}, {
    field: 'customName',
    title: '姓名/全名'
}, {
    field: 'birthday',
    title: '出生日/註冊日'
}, {
    field: 'eName',
    title: '英文名'
}, {
    field: 'countryName',
    title: '國籍/註冊地'
}, {
    field: 'majorName',
    title: '職業/行業別'
}, {
    field: 'positionName',
    title: '職稱'
}, {
    field: 'doorNo',
    title: '門牌'
}, {
    field: 'phone',
    title: '通訊電話'
}, {
    field: 'mphone',
    title: '手機'
}, {
    field: 'email',
    title: 'EMAIL'
}, {
    field: 'address1',
    title: '戶籍地址'
}, {
    field: 'address2',
    title: '通訊地址'
}, {
    field: 'fundsSrc',
    title: '資金來源'
}, {
    field: 'foreignerReason',
    title: '外國人交易目的'
}, {
    field: 'agentReason',
    title: '指定第三人原因'
}, {
    field: 'amlLV',
    title: '風險等級'
}, {
    field: 'amlResult',
    title: '比對結果'
}, ];

var colsBen = [{
    checkbox: true
}, {
    field: 'no',
    title: '編號'
}, {
    field: 'customName',
    title: '所屬購買人'
}, {
    field: 'benType',
    title: '身分別'
}, {
    field: 'benName',
    title: '姓名'
}, {
    field: 'benNo',
    title: '身分證號'
}, {
    field: 'benBirthday',
    title: '生日'
}, {
    field: 'benCountryName',
    title: '國別'
}, {
    field: 'benType2',
    title: '對象別'
}, ];