server:
  port: 8081

#spring:#  datasource:#    driver-class-name: 'com.microsoft.sqlserver.jdbc.SQLServerDriver'
#    url: 'jdbc:sqlserver://localhost;databaseName=kandawaps'
#    username: 'kanda'
#    password: 'kanda1723'
#  jpa: 
#    show-sql: true
#    properties: 
#      hibernate:
#       format_sql: true
#       dialect: 'org.hibernate.dialect.SQLServer2012Dialect'
#       ddl-auto: 'update'